### PR TITLE
Added an interface for saving xmlobject objects to zip

### PR DESCRIPTION
**Pull request by whatever098**

### CODE REVIEW

**Comment by pjfanning** [comment]
Please do open PRs without providing a detailed justification for them.

I am struggling to see what this achieves. XMLBeans has support already for creating jars.

**Comment by pjfanning** [comment]
Why, for instance, can't you just use `save(OutputStream os, XMLOptions options)`. You can provide your own ZipOutputStream as input to this existing method.

**Comment by whatever098** [comment]
These are changes made by someone else on my team, I will ask him for a response

**Comment by whatever098** [comment]
This PR can be ignored. This change is due to my teammates not finding the save(OutputStream os, XMLOptions options) method.

**Pull request closed without merging**
